/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import command.CancelarPedidoCommand;
import command.CrearPedidoCommand;
import command.EntregarPedidoCommand;
import command.EnviarPedidoCommand;
import command.Invoker;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Pedido;
import model.Producto;
import observer.EstadoObserver;
import observer.HistorialObserver;
import strategy.ContextoPago;
import strategy.MetodoPago;
import strategy.PagoEfectivo;
import strategy.PagoTarjeta;
import strategy.PagoYape;
import command.PagarPedidoCommand;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Pedido pedido;
    private HistorialObserver historialObserver;
    private EstadoObserver estadoObserver;
    private Invoker invoker = new Invoker();
    private ContextoPago contextoPago = new ContextoPago();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        lblEstado.setText("");
        txtHistorial.setEditable(false);
        historialObserver = new HistorialObserver(txtHistorial);
        estadoObserver = new EstadoObserver(lblEstado);
    }

    private void actualizarIndicadores() {

        lblCreado.setForeground(Color.GRAY);
        lblPagado.setForeground(Color.GRAY);
        lblEnviado.setForeground(Color.GRAY);
        lblEntregado.setForeground(Color.GRAY);

        if (pedido == null) {
            return;
        }

        switch (pedido.getEstado()) {

            case "CREADO":

                lblCreado.setText("💚 Creado");
                lblCreado.setForeground(new Color(0, 153, 0));
                break;

            case "PAGADO":

                lblCreado.setText("💚 Creado");
                lblPagado.setText("💚 Pagado");

                lblCreado.setForeground(new Color(0, 153, 0));
                lblPagado.setForeground(new Color(0, 153, 0));
                break;

            case "ENVIADO":

                lblCreado.setText("💚 Creado");
                lblPagado.setText("💚 Pagado");
                lblEnviado.setText("💚 Enviado");

                lblCreado.setForeground(new Color(0, 153, 0));
                lblPagado.setForeground(new Color(0, 153, 0));
                lblEnviado.setForeground(new Color(0, 153, 0));
                break;

            case "ENTREGADO":

                lblCreado.setText("💚 Creado");
                lblPagado.setText("💚 Pagado");
                lblEnviado.setText("💚 Enviado");
                lblEntregado.setText("💚 Entregado");

                lblCreado.setForeground(new Color(0, 153, 0));
                lblPagado.setForeground(new Color(0, 153, 0));
                lblEnviado.setForeground(new Color(0, 153, 0));
                lblEntregado.setForeground(new Color(0, 153, 0));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spCantidad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cbMetodoPago = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cbProducto = new javax.swing.JComboBox<>();
        Cantidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scrollHistorial = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblCreado = new javax.swing.JLabel();
        lblPagado = new javax.swing.JLabel();
        lblEnviado = new javax.swing.JLabel();
        lblEntregado = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Pedidos - Saga Falabella");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Cantidad"); // NOI18N
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Cliente:");

        jLabel3.setText("Producto:");

        jLabel4.setText("Cantidad:");

        spCantidad.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)1), Byte.valueOf((byte)1), Byte.valueOf((byte)100), Byte.valueOf((byte)1)));
        spCantidad.setToolTipText("");

        jLabel5.setText("Método de Pago:");

        cbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Yape", "Efectivo" }));
        cbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodoPagoActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear Pedido");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnPagar.setText("Procesar Pago");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar Pedido");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar Pedido");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEntregar.setText("Entregar Pedido");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        btnDeshacer.setText("Deshacer");
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop Lenovo ThinkPad", "iPhone 15 Pro", "Smart TV Samsung 55\"", "Refrigeradora LG", "Lavadora Bosch" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCliente)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnCrear)
                        .addComponent(btnPagar)
                        .addComponent(btnEnviar)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnEntregar)
                        .addComponent(btnCancelar)
                        .addComponent(btnDeshacer)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnCrear, btnDeshacer, btnEntregar, btnEnviar, btnPagar, btnSalir});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrear)
                .addGap(18, 18, 18)
                .addComponent(btnPagar)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addGap(18, 18, 18)
                .addComponent(btnEntregar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnDeshacer)
                .addGap(18, 18, 18)
                .addComponent(btnSalir))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnCrear, btnDeshacer, btnEntregar, btnEnviar, btnPagar});

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SISTEMA DE GESTIÓN DE PEDIDOS");

        jPanel4.setForeground(new java.awt.Color(255, 51, 51));

        jLabel8.setText("Estado del Pedido:");

        lblEstado.setBackground(new java.awt.Color(255, 0, 0));
        lblEstado.setText("[CREADO]");

        jLabel6.setText("Historial del Pedido:");

        txtHistorial.setColumns(20);
        txtHistorial.setRows(5);
        jScrollPane1.setViewportView(txtHistorial);

        scrollHistorial.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblEstado)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 51));
        jLabel9.setText("SAGA FALABELLA");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/saga.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Seguimiento del Pedido");

        lblCreado.setText("📎 Creado");

        lblPagado.setText("📎 Pagado");

        lblEnviado.setText("📎 Enviado");

        lblEntregado.setText("📎 Entregado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(79, 79, 79))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEntregado)
                    .addComponent(lblEnviado)
                    .addComponent(lblPagado)
                    .addComponent(lblCreado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(lblCreado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPagado)
                .addGap(18, 18, 18)
                .addComponent(lblEnviado)
                .addGap(18, 18, 18)
                .addComponent(lblEntregado)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(Cantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1399, 1399, 1399)
                        .addComponent(Cantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
        // TODO add your handling code here:
        invoker.deshacer();
        if (pedido != null) {
            lblEstado.setText(pedido.getEstado());
            txtHistorial.append("Se deshizo la última acción.\n\n");
        }
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void cbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMetodoPagoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        String nombreCliente = txtCliente.getText().trim();
        String nombreProducto = cbProducto.getSelectedItem().toString();
        if (nombreCliente.isEmpty() || nombreProducto.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos.");

            return;
        }
        int cantidad = ((Number) spCantidad.getValue()).intValue();
        String metodoPago = cbMetodoPago.getSelectedItem().toString();
        Cliente cliente = new Cliente(nombreCliente);
        Producto producto;
        switch (nombreProducto) {
            case "Laptop Lenovo ThinkPad":
                producto = new Producto(nombreProducto, 3500);
                break;
            case "iPhone 15 Pro":
                producto = new Producto(nombreProducto, 4200);
                break;
            case "Smart TV Samsung 55\"":
                producto = new Producto(nombreProducto, 2500);
                break;
            case "Refrigeradora LG":
                producto = new Producto(nombreProducto, 2800);
                break;
            default:
                producto = new Producto(nombreProducto, 1900);
        }
        pedido = new Pedido(cliente, producto, cantidad, metodoPago);
        pedido.agregarObserver(historialObserver);
        pedido.agregarObserver(estadoObserver);
        CrearPedidoCommand comando = new CrearPedidoCommand(pedido);
        invoker.ejecutarComando(comando);
        actualizarIndicadores();
        lblEstado.setText(pedido.getEstado());

        txtHistorial.append("====================================\n");
        txtHistorial.append("Pedido creado\n");
        txtHistorial.append("Cliente : " + cliente.getNombre() + "\n");
        txtHistorial.append("Producto: " + producto.getNombre() + "\n");
        txtHistorial.append("Cantidad : " + cantidad + "\n");
        txtHistorial.append("Precio Unitario : S/. " + producto.getPrecio() + "\n");
        txtHistorial.append("TOTAL : S/. " + pedido.calcularTotal() + "\n");
        txtHistorial.append("Pago    : " + metodoPago + "\n");
        txtHistorial.append("Estado  : " + pedido.getEstado() + "\n\n");
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        if (pedido == null) {

            JOptionPane.showMessageDialog(this,
                    "Primero debe crear un pedido.");
            return;
        }

        MetodoPago metodo;
        String opcion = cbMetodoPago.getSelectedItem().toString();
        switch (opcion) {
            case "Tarjeta":
                metodo = new PagoTarjeta();
                break;
            case "Yape":
                metodo = new PagoYape();
                break;
            default:
                metodo = new PagoEfectivo();
                break;
        }

        contextoPago.setMetodoPago(metodo);
        double monto = pedido.calcularTotal();
        contextoPago.procesarPago(monto);
        PagarPedidoCommand comando = new PagarPedidoCommand(pedido);
        invoker.ejecutarComando(comando);
        actualizarIndicadores();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        if (pedido == null) {
            JOptionPane.showMessageDialog(this,
                    "Primero cree un pedido.");
            return;
        }

        if (!pedido.estaPagado()) {
            JOptionPane.showMessageDialog(this,
                    "Debe procesar el pago primero.");
            return;
        }
        EnviarPedidoCommand comando
                = new EnviarPedidoCommand(pedido);

        invoker.ejecutarComando(comando);
        actualizarIndicadores();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
        if (pedido == null) {
            JOptionPane.showMessageDialog(this,
                    "Primero cree un pedido.");
            return;
        }

        if (!pedido.estaEnviado()) {
            JOptionPane.showMessageDialog(this,
                    "Debe enviar primero el pedido.");
            return;
        }
        EntregarPedidoCommand comando
                = new EntregarPedidoCommand(pedido);
        invoker.ejecutarComando(comando);
        actualizarIndicadores();
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (pedido == null) {
            JOptionPane.showMessageDialog(this,
                    "No existe un pedido.");
            return;

        }

        if (pedido.estaEntregado()) {
            JOptionPane.showMessageDialog(this,
                    "Un pedido entregado no puede cancelarse.");
            return;
        }
        CancelarPedidoCommand comando
                = new CancelarPedidoCommand(pedido);

        invoker.ejecutarComando(comando);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbMetodoPago;
    private javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreado;
    private javax.swing.JLabel lblEntregado;
    private javax.swing.JLabel lblEnviado;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblPagado;
    private javax.swing.JScrollPane scrollHistorial;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextArea txtHistorial;
    // End of variables declaration//GEN-END:variables
}
